var games = [
"Stardew Valley (a community game)",
"Minecraft (a building game)",
"Pokemon Go (an augmented reality game about collecting creatures) ",
"Tennis (a sport game where two opponents use rackets to hit a ball back and forth on a court, trying to get the other player to miss the ball)",
"Basketball (team sport)",
"Baseball (team sport)",
"Football (team sport)",
"Soccer (team  sport)",
"Battleship (strategy board game)",
"Centipede (arcade shooter game)",
"Chess (strategy board game)",
"Operation (physical skill board game)",
"Pac-Man (arcade maze game)",
"Pong (arcade ball game)",
"Tetris (arcade puzzle game)",
"Scrabble (turn-based board game)",
"Fortnite (first person build/shoot game)",
"Hide and Seek (indoor/outdoor physical game)",
"Super Mario Bros (arcade platform game)",
"Megaman (arcade game)",
"Tag (indoor/outdoor physical game)",
"Who Am I? (the game where you have a name on a card on your forehead and you have to guess who you are (social guessing game)",
"Checkers (strategy board game)",
"Dance Dance Revolution (rhythm game)",
"Gran Turismo (car racing game)",
"Halo (first-person shooter game)",
"Monopoly (turn-based board game)",
"Spore (real-time strategy/simulation game)",
"The Sims (simulation game)",
"World of Warcraft (Massively Multiplayer Online RPG game)",
"Super Mario (scrolling platform game)",
"Asteroids (arcade shooter game)",
"Candy Crush (match three digital game)",
"Fruit Ninja (casual digital game)",
"Love Nikki Dress Up Queen (a dress up game with storyline)",
"Untitled Goose Game (a sandbox game where you do everything a goose does)",
  "Super Smash Bros. (a fighting game where you try to knock your opponents off the game field)",
  "Any game you know and love",
  "Civilization 6",
  "Uno (a card game)",
  "Cookie Clicker (you click cookies and buy grandmas)",
  "Papa's Pizzeria - or anything from the Papa",
  "Overwatch",
  "Valorant",
  "A Puzzle Game",
  "A Platformer",
  "An RPG",
  "An Action Game",
  "A First Person Shooter",
  "Wii Party",
  "Wordle",
  "Tamagatchi",
  "Angry Birds",
  "Assassin's Creed",
  "2048 (a numbers matching game)",
  "Neko Atsume (cat collecting game)",
  "Tic Tac Toe (you know with xs and os)",
  "Cooking Mama (You cook and mama rates your cooking)",
  
]

var verbs = [
  "Avoiding",
"Banging",
"Building",
"Bumping",
"Catching",
  "Collecting",
  "Spinning",
  "Singing",
  "Bouncing",
"Celebrating",
"Creating",
"Growing",
"Helping",
"Jumping",
  "Dancing",
  "Singing",
  "Merging",
  "Destroying",
  "Flying",
  "Searching",
"Launching",
  "Sharing",
"Trading",
"Racing",
"Collecting",
"Throwing",
"Hiding",
"Fighting",
"Sliding",
  "Banging, Sliding, Racing, Collecting, Skating AND Singing",
  "Speaking",
  "Whispering",
  "Drawing/Making Art",
  "Making Friends"
]

var challenges = [
"Time Limit",
  "The environment is not what it seems",
  "Zombies",
  "Can't stop hiccupping",
"Parenthood",
  "Graduating School",
  "Boredom",
  "Alien Cats",
  "Ran out of cash",
  "Really Fashionable Vampires",
  "Sinister TikTok Influencers",
  "Getting into college",
  "Bunnies who have lost their tails",
  "Loneliness",
  "Social Anxiety",
  "Can't find a bathroom",
  "Your hands are pancakes",
  "Your family turned into pancakes",
  "You wake up and you are a bug",
  "You can only bounce",
  "No Gravity",
  "Evil fish",
  "Smelly socks",
  "Subway is delayed",
  "School",
  "Too much to do, too little time",
  "Enemies are invisible, you can only hear them",
  "Everything is too cute",
  "Broken limbs",
  "Potato Chip explosion",
   "You get embarassed really easily",
  "The ground is made of lava",
    "Parents banned your screen time",
]

var values = [
  "Caring",
"Health",
"Resilience",
"Trust",
"Accountability",
"Autonomy",
"Community",
"Confidence",
"Creativity",
  "Family",
    "Chosen Family",
  "Heritage",
"Dependability",
"Initiative ",
"Dignity",
"Efficiency",
"Freedom",
"Generosity",
"Happiness",
"Humility",
"Humor",
"Individualism",
"Justice",
"Open-mindedness",
"Perseverance",
"Peace",
"Privacy",
"Sustainability",
  "Sharing",
"Style",
"Respect",
"Sympathy",
"Tenacity",
"Decisiveness",
"Tradition",
"Wealth",
"Independence",
  "Friendship",
  "Identity",
  "Teaching"
  
]


var shuffle = document.getElementById("shuffle");
var game = document.getElementById("game");
var verb = document.getElementById("verb");
var challenge = document.getElementById("challenge");
var value = document.getElementById("value");

shuffle.addEventListener("click", function(){
  var randomGame = Math.floor(Math.random() * games.length);
  var randomVerb = Math.floor(Math.random() * verbs.length);
  var randomChallenge = Math.floor(Math.random() * challenges.length);
  var randomValue = Math.floor(Math.random() * values.length);
  
  game.innerHTML = games[randomGame];
  verb.innerHTML = verbs[randomVerb];
  challenge.innerHTML = challenges[randomChallenge];
  value.innerHTML = values[randomValue];
  document.activeElement.blur()
});